@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-18 18:37
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=AI Work Browser"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMTggMTg6MzcNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9QUkgV29yayBCcm93
        echo c2VyIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiRU5UUllfTU9ERT1maWxlIg0Kc2V0ICJB
        echo UFBfRU5UUlk9bWFpbi5weSINCnNldCAiUlVOTkVSX0FSR1M9Ig0KDQpzZXQgIlBZPSVDRCVcJVZF
        echo TlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAg
        echo IGVjaG8gW0VSUk9SXSBMb2NhbCB2ZW52IG5vdCBmb3VuZDogIiVQWSUiDQogICAgZWNoby4NCiAg
        echo ICBlY2hvIEZpeCB3aXRoOg0KICAgIGVjaG8gICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSIN
        echo CiAgICBlY2hvICAgIiVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIiAtbSBwaXAgaW5zdGFs
        echo bCAtLXVwZ3JhZGUgcGlwDQogICAgZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4
        echo ZSIgLW0gcGlwIGluc3RhbGwgLXIgcmVxdWlyZW1lbnRzLnR4dA0KICAgIGVjaG8uDQogICAgcGF1
        echo c2UNCiAgICBleGl0IC9iIDENCikNCg0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJmaWxlIiBpZiBu
        echo b3QgZXhpc3QgIiVBUFBfRU5UUlklIiAoDQogICAgZWNobyBbRVJST1JdIEVudHJ5IGZpbGUgbm90
        echo IGZvdW5kOiAiJUFQUF9FTlRSWSUiDQogICAgZWNobyBFZGl0IHJ1bi5iYXQgb3IgcnVuIHdpdGgg
        echo dGhlIGNvcnJlY3QgZW50cnkgZmlsZS4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0KDQp0
        echo aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBSVU4iDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUnVubmluZyA6ICVQ
        echo Uk9KRUNUX05BTUUlDQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNobyAgUHl0aG9uICA6ICVQWSUN
        echo CmVjaG8gIE1vZGUgICAgOiAlRU5UUllfTU9ERSUNCmVjaG8gIEVudHJ5ICAgOiAlQVBQX0VOVFJZ
        echo JQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJydW5uZXIiIGVjaG8gIEFyZ3MgICAgOiAlUlVOTkVS
        echo X0FSR1MlDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0Kc2V0ICJFWElUQ09ERT0wIg0KDQppZiAvSSAiJUVO
        echo VFJZX01PREUlIj09Im1vZHVsZSIgKA0KICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAlKg0KKSBl
        echo bHNlIGlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiAoDQogICAgaWYgZGVmaW5lZCBSVU5O
        echo RVJfQVJHUyAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAhUlVOTkVSX0FSR1MhICUq
        echo DQogICAgKSBlbHNlICgNCiAgICAgICAgIiVQWSUiIC1tICVBUFBfRU5UUlklICUqDQogICAgKQ0K
        echo KSBlbHNlICgNCiAgICAiJVBZJSIgIiVBUFBfRU5UUlklIiAlKg0KKQ0KDQpzZXQgIkVYSVRDT0RF
        echo PSFFUlJPUkxFVkVMISINCg0KZWNoby4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9jZXNzIGV4aXRlZCB3
        echo aXRoIGNvZGU6ICFFWElUQ09ERSENCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAhRVhJVENPREUh
        echo DQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMTggMTg6MzcNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTE4
        echo IDE4OjM3DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9QUkgV29yayBCcm93c2VyIg0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiQUNUSVZB
        echo VEU9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNcYWN0aXZhdGUuYmF0Ig0KDQppZiBub3QgZXhpc3Qg
        echo IiVBQ1RJVkFURSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMgbm90IGZvdW5k
        echo Og0KICAgIGVjaG8gICAgICAgICAiJUFDVElWQVRFJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3Jl
        echo YXRlIGl0IHdpdGg6DQogICAgZWNobyAgICAgICAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIl
        echo Ig0KICAgIGVjaG8uDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9K
        echo RUNUX05BTUUlIC0gVkVOViBTSEVMTCINCmNhbGwgIiVBQ1RJVkFURSUiDQoNCmVjaG8gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpl
        echo Y2hvICBQcm9qZWN0IHNoZWxsIGFjdGl2YXRlZA0KZWNobyAgUHJvamVjdDogIiVDRCUiDQplY2hv
        echo ICBQeXRob24gOg0Kd2hlcmUgcHl0aG9uDQplY2hvICBUeXBlICJleGl0IiB0byBsZWF2ZSB0aGlz
        echo IHNoZWxsLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT0NCmVjaG8uDQpjbWQgL2sNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0xOCAxODozNw0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1BSSBXb3Jr
        echo IEJyb3dzZXIiDQpzZXQgIlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVc
        echo U2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtF
        echo UlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBD
        echo cmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQog
        echo ICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUgIiVQUk9KRUNUX05BTUUlIC0gU1lO
        echo QyINCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT0NCmVjaG8gIFN5bmNpbmc6ICVQUk9KRUNUX05BTUUlDQplY2hvICBQeXRo
        echo b24gOiAlUFklDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PQ0KZWNoby4NCg0KZWNobyBbMS8zXSBVcGdyYWRpbmcgcGlwLi4u
        echo DQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBpbnN0YWxsIC0tdXBncmFkZSBwaXANCmVjaG8uDQoN
        echo CmlmIGV4aXN0ICJyZXF1aXJlbWVudHMudHh0IiAoDQogICAgZWNobyBbMi8zXSBJbnN0YWxsaW5n
        echo IGZyb20gcmVxdWlyZW1lbnRzLnR4dC4uLg0KICAgIGVjaG8gPT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQogICAgIiVQWSUiIC1tIHBp
        echo cCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KKSBlbHNlICgNCiAgICBl
        echo Y2hvIFsyLzNdIFNLSVBQRUQ6IE5vIHJlcXVpcmVtZW50cy50eHQgZm91bmQuDQogICAgZWNobyAg
        echo ICAgICBDcmVhdGUgb25lIHdpdGg6IHBpcC5iYXQgZnJlZXplIF4+IHJlcXVpcmVtZW50cy50eHQN
        echo CiAgICBlY2hvLg0KKQ0KDQplY2hvIFszLzNdIERlcGVuZGVuY3kgaGVhbHRoIGNoZWNrLi4uDQpl
        echo Y2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KIiVQWSUiIC1tIHBpcCBjaGVjaw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFNZ
        echo TkMgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTE4IDE4OjM3DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPUFJIFdvcmsgQnJvd3Nl
        echo ciINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9ZmlsZSINCnNldCAiQVBQ
        echo X0VOVFJZPW1haW4ucHkiDQpzZXQgIlJVTk5FUl9BUkdTPSINCnNldCAiUFk9JUNEJVwlVkVOVl9E
        echo SVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFBST0pFQ1QgRE9DVE9S
        echo OiAlUFJPSkVDVF9OQU1FJQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFByb2plY3QgOiAlQ0QlDQplY2hvICBN
        echo b2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDogJUFQUF9FTlRSWSUNCmlmIC9J
        echo ICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAgIDogJVJVTk5FUl9BUkdTJQ0K
        echo ZWNoby4NCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRkFJTF0gdmVudiBub3Qg
        echo Zm91bmQgYXQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAg
        echo ICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAgcGF1c2UNCiAgICBleGl0
        echo IC9iIDENCikNCg0KZWNobyBbT0tdIHZlbnYgZm91bmQ6ICIlUFklIg0KZWNoby4NCg0KZWNobyAt
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0NCmVjaG8gIFB5dGhvbiBFbnZpcm9ubWVudA0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtYyAiaW1wb3J0
        echo IHN5czsgcHJpbnQoJ0V4ZWN1dGFibGUgOicsIHN5cy5leGVjdXRhYmxlKTsgcHJpbnQoJ1ZlcnNp
        echo b24gICAgOicsIHN5cy52ZXJzaW9uLnNwbGl0KClbMF0pOyBwcmludCgnUHJlZml4ICAgICA6Jywg
        echo c3lzLnByZWZpeCkiDQplY2hvLg0KDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KZWNobyAgcGlwIHZlcnNpb24NCmVjaG8g
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tDQoiJVBZJSIgLW0gcGlwIC0tdmVyc2lvbg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIElu
        echo c3RhbGxlZCBQYWNrYWdlcw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgbGlzdA0KZWNoby4NCg0K
        echo ZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0NCmVjaG8gIERlcGVuZGVuY3kgSGVhbHRoDQplY2hvIC0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIiVQWSUiIC1tIHBp
        echo cCBjaGVjaw0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIEVudHJ5IFBvaW50IENoZWNrDQplY2hv
        echo IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLQ0KaWYgL0kgIiVFTlRSWV9NT0RFJSI9PSJmaWxlIiAoDQogICAgaWYgZXhpc3QgIiVBUFBf
        echo RU5UUlklIiAoDQogICAgICAgIGVjaG8gW09LXSBFbnRyeSBmaWxlIGZvdW5kOiAiJUFQUF9FTlRS
        echo WSUiDQogICAgKSBlbHNlICgNCiAgICAgICAgZWNobyBbRkFJTF0gRW50cnkgZmlsZSBOT1QgZm91
        echo bmQ6ICIlQVBQX0VOVFJZJSINCiAgICApDQopIGVsc2UgKA0KICAgICIlUFklIiAtYyAiaW1wb3J0
        echo IGltcG9ydGxpYi51dGlsLCBzeXM7IG5hbWU9ciclQVBQX0VOVFJZJSc7IHNwZWM9aW1wb3J0bGli
        echo LnV0aWwuZmluZF9zcGVjKG5hbWUpOyBwcmludCgoJ1tPS10gTW9kdWxlIGZvdW5kOiAnIGlmIHNw
        echo ZWMgZWxzZSAnW0ZBSUxdIE1vZHVsZSBOT1QgZm91bmQ6ICcpICsgbmFtZSk7IHN5cy5leGl0KDAg
        echo aWYgc3BlYyBlbHNlIDEpIiAyPm51bA0KICAgIGlmIGVycm9ybGV2ZWwgMSBlY2hvIFtGQUlMXSBN
        echo b2R1bGUgaW1wb3J0IHRlc3QgZmFpbGVkLg0KICAgIGlmIC9JICIlRU5UUllfTU9ERSUiPT0icnVu
        echo bmVyIiBlY2hvIFtJTkZPXSBSdW5uZXIgYXJnczogIiVSVU5ORVJfQVJHUyUiDQopDQplY2hvLg0K
        echo DQplY2hvIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLQ0KZWNobyAgUHJvamVjdCBGaWxlcw0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmlmIGV4aXN0ICJ1di5s
        echo b2NrIiAgICAgICAgICBlY2hvIFtPS10gICB1di5sb2NrIGZvdW5kDQppZiBleGlzdCAicHlwcm9q
        echo ZWN0LnRvbWwiICAgZWNobyBbT0tdICAgcHlwcm9qZWN0LnRvbWwgZm91bmQNCmlmIGV4aXN0ICJy
        echo ZXF1aXJlbWVudHMudHh0IiBlY2hvIFtPS10gICByZXF1aXJlbWVudHMudHh0IGZvdW5kDQppZiBu
        echo b3QgZXhpc3QgInJlcXVpcmVtZW50cy50eHQiIGVjaG8gW1dBUk5dIHJlcXVpcmVtZW50cy50eHQg
        echo bWlzc2luZw0KZWNoby4NCg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIERPQ1RPUiBDT01QTEVURQ0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCnBhdXNlDQpleGl0IC9iIDANCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMTggMTg6MzcNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1BSSBXb3JrIEJyb3dzZXIiDQpzZXQgIlZFTlZf
        echo RElSPS52ZW52Ig0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJUiVcU2NyaXB0c1xweXRob24uZXhlIg0K
        echo DQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hvIFtFUlJPUl0gTG9jYWwgdmVudiB3YXMg
        echo bm90IGZvdW5kOg0KICAgIGVjaG8gICAgICAgICAiJVBZJSINCiAgICBlY2hvLg0KICAgIHBhdXNl
        echo DQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFRFU1QiDQplY2hv
        echo ID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PQ0KZWNobyAgVGVzdGluZzogIiVQUk9KRUNUX05BTUUlIg0KZWNobyAgUHl0aG9uIDogIiVQ
        echo WSUiDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PQ0KZWNoby4NCiIlUFklIiAtbSBweXRlc3QgLXYgJSoNCnNldCAiRVhJVENP
        echo REU9JUVSUk9STEVWRUwlIg0KDQplY2hvLg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmlmICIlRVhJVENPREUlIj09IjAi
        echo ICgNCiAgICBlY2hvICBURVNUUyBQQVNTRUQNCikgZWxzZSAoDQogICAgZWNobyAgVEVTVFMgRkFJ
        echo TEVEICBeKGV4aXQgY29kZTogJUVYSVRDT0RFJV4pDQopDQplY2hvID09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQg
        echo L2IgJUVYSVRDT0RFJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
